# Generated by Django 4.1.3 on 2022-11-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faleconosco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('motivo', models.CharField(max_length=30, verbose_name='Qual motivo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('cpf', models.CharField(help_text='CPF - Ex: 1234567891011', max_length=11, unique=True)),
                ('celular', models.CharField(help_text='Numero para contato', max_length=12)),
                ('mensagem', models.TextField(help_text='Mensagem')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
    ]
